Quickfix for EL7 buildroot issue
...
copying static files...
Exception occurred:
  File "/usr/lib64/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff', '/builddir/build/BUILD/networkx-1.10/doc/build/html/_static/fonts/fontawesome-webfont.woff', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff'"), ('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg', '/builddir/build/BUILD/networkx-1.10/doc/build/html/_static/fonts/fontawesome-webfont.svg', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg'")]

Missing files are in fontawesome-fonts-web which for some reason is pulled
 into f22 buildroot but not el7??
Quickfix until fully debugged will be explicit BR in python-networkx.spec